<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Revenant_Theme_Studio</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>IconEngine\icons\Logos\RTS2.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
	<Compile Remove="IconEngine\**\*.cs" />
    <Resource Include="IconEngine\icons\Logos\RTS2.ico" />
	<None Remove="IconEngine\icons\Logos\RTS2.ico" />
  </ItemGroup>

</Project>